
package cl.amsa.ws.ariba2.network.pxe10005_purchaseorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrderBindingQSService", targetNamespace = "http://ws.aminerals.cl/Ariba/Network/PXE10005_PurchaseOrder", wsdlLocation = "file:/Users/betsytrujillo/Documents/Invoke/AMSA/Fuentes/AMSAMigracion/Ariba/WSDL/PXE10005_PurchaseOrder.wsdl")
public class PurchaseOrderBindingQSService
    extends Service
{

    private final static URL PURCHASEORDERBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERBINDINGQSSERVICE_EXCEPTION;
    private final static QName PURCHASEORDERBINDINGQSSERVICE_QNAME = new QName("http://ws.aminerals.cl/Ariba/Network/PXE10005_PurchaseOrder", "PurchaseOrderBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/betsytrujillo/Documents/Invoke/AMSA/Fuentes/AMSAMigracion/Ariba/WSDL/PXE10005_PurchaseOrder.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERBINDINGQSSERVICE_WSDL_LOCATION = url;
        PURCHASEORDERBINDINGQSSERVICE_EXCEPTION = e;
    }

    public PurchaseOrderBindingQSService() {
        super(__getWsdlLocation(), PURCHASEORDERBINDINGQSSERVICE_QNAME);
    }

    public PurchaseOrderBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERBINDINGQSSERVICE_QNAME, features);
    }

    public PurchaseOrderBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERBINDINGQSSERVICE_QNAME);
    }

    public PurchaseOrderBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERBINDINGQSSERVICE_QNAME, features);
    }

    public PurchaseOrderBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrderBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrderPT
     */
    @WebEndpoint(name = "PurchaseOrderBindingQSPort")
    public PurchaseOrderPT getPurchaseOrderBindingQSPort() {
        return super.getPort(new QName("http://ws.aminerals.cl/Ariba/Network/PXE10005_PurchaseOrder", "PurchaseOrderBindingQSPort"), PurchaseOrderPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrderPT
     */
    @WebEndpoint(name = "PurchaseOrderBindingQSPort")
    public PurchaseOrderPT getPurchaseOrderBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.aminerals.cl/Ariba/Network/PXE10005_PurchaseOrder", "PurchaseOrderBindingQSPort"), PurchaseOrderPT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERBINDINGQSSERVICE_EXCEPTION!= null) {
            throw PURCHASEORDERBINDINGQSSERVICE_EXCEPTION;
        }
        return PURCHASEORDERBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
